import random

a = ["ok chị đừng muốn hào hứng",
     "vâng chị muốn có thể đừng hứng thú",
     "ok xin lỗi lắm",
     "bây giờ muốn hào hứng",
     "tò mò người",
     "tò mò nhu cầu",
     "chị cứ hứng thú",
     "tôi gọi nữa",
     "bác biết nữa",
     "chú bỏ lỡ nữa",
     "cứ hứng thú",
     "ok bỏ lỡ lắm",
     "đang tò mò nhu cầu",
     "cứ không hào hứng",
     "vâng bác cứ tò mò lắm",
     "xin lỗi cho chị",
     "chị có thể hứng thú",
     "gặp bận",
     "sáng giờ bỏ lỡ về tôi",
     "sáng giờ gặp hứng thú",
     "có thể rất thích hào hứng",
     "vâng bác đừng bỏ lỡ lắm",
     "vâng tôi biết người",
     "ok gặp bận",
     "sáng giờ bác muốn hứng thú",
     "sáng giờ bác không bận",
     "vâng cô xin lỗi về anh",
     "sáng giờ tôi tò mò chú",
     "bây giờ cô nghe cho bác",
     "ok anh bỏ lỡ nữa",
     "sáng giờ không bận",
     "vâng cô đừng hào hứng",
     "ok bác biết lắm",
     "tôi có thể bực",
     "chú không biết lắm",
     "tôi không thích nghe lắm",
     "bác không nghe nữa",
     "không muốn tò mò",
     "tôi không muốn bỏ lỡ lắm",
     "chị ghét nghe lắm",
     "vâng không muốn nghe lắm",
     "nãy giờ có thể bận",
     "bây giờ không thích gọi",
     "chú không chán",
     "bác có thể nghe lắm",
     "vâng muốn gọi",
     "tôi đang cay cú",
     "không muốn nói",
     "vâng chị đang cay cú",
     "bây giờ không muốn nghe",
     "chú không bận",
     "muốn nói",
     "bây giờ ghét bưc bội",
     "chú muốn bận",
     "tôi cứ cay cú",
     "nãy giờ cô thích bưc bội",
     "chú đừng nghe nữa",
     "cô không thích nghe",
     "ok không thích tò mò nữa",
     "thích nghe lắm",
     "đang bận",
     "bác có thể tức giận",
     "chú không nghe nữa",
     "có thể bưc bội",
     "cô không hào hứng",
     "ok bác đang hứng thú",
     "đừng bỏ lỡ",
     "cô không bỏ lỡ nữa",
     "tôi đừng nghe nữa",
     "chú không muốn nghe",
     "không muốn nghe nữa",
     "đừng tức giận",
     "bây giờ không thích nghe",
     "nãy giờ không thích nghe",
     "ok chị không cay cú",
     "ok anh đang tức giận",
     "đang bưc bội",
     "không thích gọi",
     "anh không thích nghe"]

print(random.shuffle(a))
print(a)

with open("./input/sentences.txt", "+w", encoding="utf-8") as file:
     for line in a:
          file.write(line + "\n")
